name: Entregables

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Setup de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Crear entorno virtual
        run: python -m venv venv

      - name: Activar entorno y actualizar pip
        run: |
          ./venv/Scripts/activate
          python -m pip install --upgrade pip

      - name: Instalar dependencias
        run: ./venv/Scripts/pip install -r requirements.txt

      - name: Ejecutar recolección de datos
        run: ./venv/Scripts/python src/proyecto_integrado_V/main.py

      - name: Ejecutar enriquecimiento de datos
        run: ./venv/Scripts/python src/proyecto_integrado_V/enricher.py

      - name: Entrenar y guardar modelo
        run: ./venv/Scripts/python src/proyecto_integrado_V/modeller.py

      - name: Commit y push de cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización automática de datos TSLA + modelo"
          commit_user_name: Davinson Rincon [GitHub Actions]
          commit_user_email: davinson.rincon@est.iudigital.edu.co 
